apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki                       # 대시보드 / Explore 에서 참조하는 키
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      timeout: 60
      maxLines: 5000
