"""유저 장소 즐겨찾기 테이블 추가

Revision ID: 8197254a8569
Revises: b2087518fcbf
Create Date: 2026-04-13 12:33:05.639730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8197254a8569'
down_revision: Union[str, Sequence[str], None] = 'b2087518fcbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_place',
    sa.Column('favorite_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('place_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('favorite_id'),
    sa.UniqueConstraint('user_id', 'place_id', name='uq_user_favorite_place')
    )
    op.create_index('ix_favorite_place_id', 'favorite_place', ['place_id'], unique=False)
    op.create_index('ix_favorite_user_id', 'favorite_place', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_favorite_user_id', table_name='favorite_place')
    op.drop_index('ix_favorite_place_id', table_name='favorite_place')
    op.drop_table('favorite_place')
    # ### end Alembic commands ###
