"""Classmate 게시글, 좋아요, 이미지 관련 테이블 추가

Revision ID: a89d4f05a8fa
Revises: d00557f2cb96
Create Date: 2026-04-07 14:13:59.185209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a89d4f05a8fa'
down_revision: Union[str, Sequence[str], None] = 'd00557f2cb96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tripmate_post',
    sa.Column('post_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('preferred_age_min', sa.Integer(), nullable=False),
    sa.Column('preferred_age_max', sa.Integer(), nullable=False),
    sa.Column('preferred_gender', sa.Enum('MALE', 'FEMALE', 'ANY', name='preferredgender'), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('travel_start_date', sa.Date(), nullable=False),
    sa.Column('travel_end_date', sa.Date(), nullable=False),
    sa.Column('companion_type', sa.Enum('FRIEND', 'FAMILY', 'COUPLE', 'SOLE', name='companiontype'), nullable=False),
    sa.Column('is_displayed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(content) >= 10', name='ck_content_min_length'),
    sa.CheckConstraint('preferred_age_min <= preferred_age_max', name='ck_preferred_age_range'),
    sa.CheckConstraint('travel_start_date <= travel_end_date', name='ck_travel_date_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_index('ix_tripmate_post_region', 'tripmate_post', ['region'], unique=False)
    op.create_index('ix_tripmate_post_travel_dates', 'tripmate_post', ['travel_start_date', 'travel_end_date'], unique=False)
    op.create_index('ix_tripmate_post_user_id', 'tripmate_post', ['user_id'], unique=False)
    op.create_table('tripmate_post_image',
    sa.Column('image_id', sa.String(length=50), nullable=False),
    sa.Column('post_id', sa.String(length=50), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('image_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['tripmate_post.post_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_index('ix_tripmate_post_image_post_id', 'tripmate_post_image', ['post_id'], unique=False)
    op.create_table('tripmate_post_like',
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('post_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['tripmate_post.post_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.create_index('ix_tripmate_post_like_post_id', 'tripmate_post_like', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tripmate_post_like_post_id', table_name='tripmate_post_like')
    op.drop_table('tripmate_post_like')
    op.drop_index('ix_tripmate_post_image_post_id', table_name='tripmate_post_image')
    op.drop_table('tripmate_post_image')
    op.drop_index('ix_tripmate_post_user_id', table_name='tripmate_post')
    op.drop_index('ix_tripmate_post_travel_dates', table_name='tripmate_post')
    op.drop_index('ix_tripmate_post_region', table_name='tripmate_post')
    op.drop_table('tripmate_post')
    # ### end Alembic commands ###
